### ISSUE TITLE
Click popover bug

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#242]
**Describe the bug**
Popover does not disappear correctly.

**To Reproduce**
Steps to reproduce the behavior.

Case 1
1. Go to 'Popover > Triggering'
2. Click on button 'Click popover'
3. Click on button 'Click popover' again
4. Popover doesn't disappear

Case 2
1. Go to 'Popover > Triggering'
2. Click on button 'Click popover'
3. Click on popover body
4. Click outside
5. Popover doesn't disappear

**Expected behavior**
In both above cases popover should disappear.

**Comment by jjagielka** [comment]
I have implemented those at https://flowbite-svelte.com/components/popover#Triggering so you can compare.

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

I've fixed the issue (https://github.com/themesberg/flowbite/commit/961096580f25d04480419e2289a91f369f883f5a) when you click outside the popover component not closing. On the other hand, I would argue against toggling the visibility of the popover when clicking on the trigger element - the reason for this is because we also show it when clicking AND focusing it, meaning that even if you click it one, twice, or three times the element is still focused.

This in comparison with the dropdown component where we actually toggle the visibility of the dropdown is different because we don't show the dropdown menu when focusing the button, but only when there's an explicit action of opening it by hitting "ENTER" for keyboards or by clicking it via the mouse.

The Popover is different compared to the Dropdown from this POV - if you want to use the toggle functionality you can just use the Dropdown component instead - otherwise there would be no substantial difference between the two other than how we describe it and how the examples look.

Cheers,
Zoltan

**Comment by abellee** [comment]
if Click outside of browser Popover doesn't disappear, is this right?
