### ISSUE TITLE
Tooltip not closing on mobile Device Safari

### ISSUE THREAD

**Issue by HannesEURESA** [themesberg/flowbite#246]
The Tooltip is not closing after opeining on mobile Device on Safari Browsers. Also not on your own Site.

**Expected behavior**
Clicking away to close the tooltip. Or is there a way to give the Tooltip a close Button? 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 MPro Max, iPhone 12 pro Max IPhone 13 & 13 pro Max tested]
 - OS: [Latest 15.6]
 - Browser chrome, safari, firefox

**Comment by zoltanszogyenyi** [comment]
Hey @HannesEURESA,

Thanks for reporting - I'll test this out myself and provide a fix if needed.

**Comment by zoltanszogyenyi** [comment]
Hello @HannesEURESA,

I've fixed this issue (https://github.com/themesberg/flowbite/commit/db093b96c9e2aa653b30ed9ed4e9d68c474ec172) by introducing an event checking for clicks outside of the tooltip component. This didn't work on Safari because on mobile devices it does not support focus and blur events on the button component.

This will be released in the upcoming `v1.6.3` version of Flowbite.

Cheers,
Zoltan
