### ISSUE TITLE
Typo in https://flowbite.com/docs/components/tabs/#full-width-tabs

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite#261]
https://flowbite.com/docs/components/tabs/#full-width-tabs has unnecessary code.
Please remove the following:

```
<div class="sm:hidden">
    <label for="tabs" class="sr-only">Select your country</label>
    <select id="tabs" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option>Profile</option>
        <option>Canada</option>
        <option>France</option>
        <option>Germany</option>
    </select>
</div>
```

**Comment by Arun9650** [comment]
I like to work on that issue

**Comment by Arun9650** [comment]
so we need to change the option typo with appropriate tab names, am I right?

**Comment by zoltanszogyenyi** [comment]
Hello @Arun9650,

Thanks for opening up the issue.

It's not unnecessary code, it's a select input element instead of the tabs showing up on mobile.

<img width="880" alt="Screenshot 2022-09-12 at 12 26 41" src="https://user-images.githubusercontent.com/8052108/189619788-606e61fb-a581-4577-ad61-2122c08a83f6.png">
