### ISSUE TITLE
Unable to use Nested Accordions

### ISSUE THREAD

**Issue by dimitriharding** [themesberg/flowbite#266]
**Describe the bug**
While I am not sure if this is an issue, or maybe it's just a limited with the current Flowbit Accordion. Tried creating nested Accordions and ensuring that all of the ids used are unique and match the correct group of elements, but once you try to click the child  Accordion to open it up, it closes the parent. 

**To Reproduce**
1. Go to example: https://typescript-prfna8.stackblitz.io/
2. See HTML: https://stackblitz.com/edit/typescript-prfna8?file=index.ts

**Expected behavior**
Should be able to have nested Accordion, and child can open and close as expected without closing parent.

**Screenshots**
<img width="1036" alt="nested" src="https://user-images.githubusercontent.com/12203794/187616732-9140cc7b-84a7-4825-9dca-f221bc03de6c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome 
 - Version : 104.0.5112.101

**Additional context**
Bootstrap example: https://codepen.io/WinterSilence/pen/abpopXa

**Comment by zoltanszogyenyi** [comment]
Hey @dimitriharding,

I'll check this out. It may be a bug, a limitation of the Accordion API or you may have missed an id or attribute.

I'll get back with this.

**Comment by sdejewski10** [comment]
@zoltanszogyenyi Any update on this bug? Is there a workaround for using nested accordions with Flowbite?

**Comment by ZiTAL** [comment]
same here, using nested accordions triggered the parent accordion event

**Comment by jneuendorf** [comment]
I can reproduce the issue. The reason seems to be that all `[data-accordion-target]` descendants are considered items instead of just the "direct children".

For nesting, it would be required to associate all `[data-accordion-target]`s with their closest `[data-accordion]` parent. The code would looks something like this:


```typescript
const targetCandidates = [
    ...$accordionEl.querySelectorAll('[data-accordion-target]'),
] as HTMLElement[]

// Group items by closest accordion parent to make nested accordions work.
const items = targetCandidates
    .filter(
        ($triggerEl) =>
            $triggerEl.closest('[data-accordion]') === $accordionEl,
    )
    .map(
        ($triggerEl): AccordionItem => ({
            id: $triggerEl.getAttribute('data-accordion-target'),
            triggerEl: $triggerEl,
            targetEl: document.querySelector(
                $triggerEl.getAttribute('data-accordion-target'),
            ),
            iconEl: $triggerEl.querySelector(
                '[data-accordion-icon]',
            ),
            active:
                $triggerEl.getAttribute('aria-expanded') === 'true'
                    ? true
                    : false,
        }),
    )
```

This should the fix parent-child relation, however it doesn't work for me yet. 😕

**Comment by jneuendorf** [comment]
I had the time to update Flowbite and verify that nested accordions work.

However, in addition to init functions attached to `window` (new feature) in the same release (1.6.6, it would be very helpful to be able to access initialized components (not only accordions). The following options come to my mind:

1. like a static member of e.g. `Accordion`: `window.Accordion.instances`
2. via a function-based API, e.g. `window.Accordion.getInstances()`

Since there are already quite a few Flowbite variables attached to `window`, a namespace would reduce the window-namespace pollution: `window.Flowbite.Accordion` etc.

@zoltanszogyenyi Should I open a new issue for this feature request?

**Comment by zoltanszogyenyi** [comment]
We have nested accordions:

https://flowbite.com/docs/components/accordion/#nesting-accordions
