### ISSUE TITLE
Component classes

### ISSUE THREAD

**Issue by Garito** [themesberg/flowbite#275]
**Is your feature request related to a problem? Please describe.**

I has thinking that flowbite provides component classes (ala bootstrap) instead of using a bunch of tailwind ones

**Describe the solution you'd like**

Instead of ```bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900```
I has expecting ```navbar```

**Describe alternatives you've considered**

Would be ok to me if there is another project that do what I'm asking. Flowbite design is nice

**Additional context**

I've tried to migrate from daisyui and stop due to this issue that makes it super hard to me to do so

**Comment by zoltanszogyenyi** [comment]
Hey @Garito,

This is something that we've decided from the beginning to keep Flowbite a pure Tailwind CSS class library without adding our own class name system on top of it, because it would also beat the purpose of one of Tailwind's main advantages compared to other libraries: not having to remember unique class names other than the utility classes.

That being said, we may at some point launch a fork of Flowbite where we'll give these type of classes like `navbar` or `btn` for those who would prefer using it this way.

**Comment by Garito** [comment]
Thank
Would be nice if, it happens, someone put the link or a reference here...
