### ISSUE TITLE
Dropdowns - format tweaks

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite#276]
**Describe the bug**
`Dropdown` is like a `List group` merged with `Tooltip` (or rather `Popover`). However it does not look consistent with those:
- rounding: `Dropdown` uses class `rounded` while `List group`, `Tooltip`, `Popover` and even `Card`, `Button`, `Toast` and `Modal` all use `rounded-lg`
- space filling: `List group` fills the parent space fully i.e. first and last item are rounded in accordance with parent rounding. `Dropdown` however uses `py-1` on the parent, preventing items to fill the space fully (look at the hovering).

**To Reproduce**
1. Go to [Dropdown](https://flowbite.com/docs/components/dropdowns/) and play with the hover
2. Go to [List Group with icons](https://flowbite.com/docs/components/dropdowns/) and play with the hover
3. Observe the differences

**Expected behavior**
`Dropdown` to look more like `List group`

**Screenshots**

![image](https://user-images.githubusercontent.com/6282254/189131050-c7e78dec-3ea5-46ab-9a8b-266d65ca2b02.png)

**Additional context**

**Comment by zoltanszogyenyi** [comment]
Hey @jjagielka,

Thanks for the feedback.

This is something I'll have to pass by the design team.

@robert1508 what do you think?

**Comment by robert1508** [comment]
Hello there,

When there are no lines between the nav items, additional space must be placed to have visual consistency between the nav items and the dropdown menu itself. But of course, we will also add a variant similar to List group.

**Comment by jjagielka** [comment]
Even button is rounded-lg and looks strange with rounded only dropdown. 

![image](https://user-images.githubusercontent.com/6282254/189676127-a8ec7f91-199e-4a92-ab3a-142d77ad6bad.png)

**Comment by zoltanszogyenyi** [comment]
Hello @jjagielka,

I have updated all of the dropdown components (https://github.com/themesberg/flowbite/commit/29c4ca37cfa5fd2d64a86eb4d5b259fccf948198) to now use `rounded-lg` and also added `py-2` instead of `py-1` to the spacing between the menu items to better match the distance between items. Later we will make these updates to the block collection and templates.

This will be launched and deployed on the docs when `v1.6.3` will be published.

Cheers,
Zoltan
