### ISSUE TITLE
Flowbite interfering with Tailwind

### ISSUE THREAD

**Issue by tempcoderr** [themesberg/flowbite#376]
**Describe the bug**
I have an input tag in my header and it is getting weird design after adding `require("flowbite/plugin")` in tailwind config file. My flowbite's version is 1.5.5.

**Screenshots**
Flowbite:
<img width="276" alt="Flowbite" src="https://user-images.githubusercontent.com/117140065/209826647-03575c2a-a96c-4aeb-9542-b037c93967cf.png">
Without Flowbite:
<img width="272" alt="Tailwind" src="https://user-images.githubusercontent.com/117140065/209826659-dc2c8b37-788e-45dc-8f4c-66d2df67be98.png">

**Additional context**
Here is my input tag code:
```js
<div className="hidden lg:flex items-center border-2 ml-3 py-1 rounded-sm">
          <div className="relative w-[18px] h-[18px] mx-3">
            <Image src="/SVG/Search.svg" alt="FB" fill />
          </div>
          <input
            type="text"
            id="search"
            name="search"
            placeholder="Search for projects or categories"
            className="w-[300px] focus:outline-none bg-white"
          />
        </div>
```
I have only noticed it interfering with the input tag, it might have affected other components too.

**Comment by zoltanszogyenyi** [comment]
Hello @tempcoderr,

Thanks for reporting this issue. The reason for this is because our plugin for Tailwind CSS automatically styles pseudo elements which are most often found for form elements and tooltips/popovers.

One solution would be to keep using Flowbite's component examples and the JavaScript file, but not include the Tailwind CSS plugin which adds these styles.

Another solution would be to override these styles in your own style file.
