### ISSUE TITLE
Popover click Not working on iphone safari

### ISSUE THREAD

**Issue by hotchilipowder** [themesberg/flowbite#413]
**Describe the bug**
The component of click popover is not working on iPhone 12 Safari.

1. Go to [triggering](https://flowbite.com/docs/components/popover/#triggering)
2. Click on 'click popover'
3. See the error that "the popover" cannot disappear by doing click other places.

**Expected behavior**
The popover content can disappear after clicking other places.

**Screenshots**
![IMG_9935](https://user-images.githubusercontent.com/11959047/212699090-24c4bc85-921b-411f-aaeb-05efe11e5201.PNG)

**Smartphone (please complete the following information):**
 - Device: [iPhone12]
 - OS: [e.g. iOS16.2]
 - Browser [safari]
 - Version [Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.]

**Comment by zoltanszogyenyi** [comment]
Hello @hotchilipowder,

Thanks for the report - I'll have this checked out in the next few days. You're also free to open a PR if you'd like to contribute to help speed things up. The functionality for the Popover component is mostly found in this file:

https://github.com/themesberg/flowbite/blob/main/src/components/popover/index.ts

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @hotchilipowder,

I've fixed this issue (https://github.com/themesberg/flowbite/commit/961096580f25d04480419e2289a91f369f883f5a) by handling the click outside of the element - the reason this happened is because Safari does not support focus and blur states on the button element.

This will be introduced with `v1.6.3` of Flowbite.

Cheers,
Zoltan
