### ISSUE TITLE
instead of toogle theme select theme between ligt dark and system theme orelse custom theme

### ISSUE THREAD

**Issue by mai1237** [themesberg/flowbite#459]
Is there a possibility to 
instead of toogle theme select theme between ligt dark and system theme orelse custom theme?

**Comment by zoltanszogyenyi** [comment]
Hello @mai1237,

That's something that you can do by setting this in the `tailwind.config.js` file as outlined in the [Flowbite Dark Mode guide](https://flowbite.com/docs/customize/dark-mode/).

Basically, you would need to use this instead of the class mode:

```
// tailwind.config.js
module.exports = {
  darkMode: 'media',
  // ...
}
```

I'll close the issue until further notice.

Cheers,
Zoltan
