### ISSUE TITLE
Drawer Visibility

### ISSUE THREAD

**Issue by marasekarim** [themesberg/flowbite#473]
I created a form contain 2 textinput inside a drawer in React project. I use Drawer API Javascript to controls show and hide of the drawer. I console.log to check visibility the drawer with `drawer.isVisible()` in textinput onchange. The bug is every time I type in textinput, drawer visibilty is set to false, but the drawer and backdrop is still showing.
If i dont type anything in textinput, the drawer and the backdrop run normally. 
But when type in textinput then visibilty is false, I close the drawer, normal. but the backdrop still showing, I have to click manually the backdrop to close it.

**Comment by nutheory** [comment]
Also experiencing this (when i click a link), and the open/close toggle stops working after that.

**Comment by evd3v** [comment]
Hello! I have another issue with Vue
I use this component - https://flowbite.com/docs/components/sidebar/#default-sidebar , and in mobile version, when I click on toggle sidebar button - two drawer-backdrops are appearing, instead of one

And as a result, when I close sidebar by clicking on the backdrop - only one is closing, but another one still exist and blocking the page.

![image](https://user-images.githubusercontent.com/52712674/224738972-8c46add1-c0cd-4453-b2cf-aa6fb96eb14f.png)

**Comment by marceloamp2** [comment]
Same issue

**Comment by ArtMin96** [comment]
Same issue

**Comment by notflip** [comment]
Any news on this? This is also happening for me! Back to modals for now then so it seems

**Comment by zoltanszogyenyi** [comment]
Hey everyone,

From the v2.1.0 release the double backdrop issue should be fixed: https://github.com/themesberg/flowbite/releases/tag/v2.1.0

Can you please try upgrading and see if the issue still persists in your local environments?

Thanks,
Zoltan
