### ISSUE TITLE
Drawer & Modal component initialization bug via data-* attribute

### ISSUE THREAD

**Issue by SiNONiMiTY** [themesberg/flowbite#589]
**Describe the bug**
Initializing the Drawer component via Javascript & via data-* attributes yield different behavior.

**To Reproduce**
See the linked reproduction
https://stackblitz.com/edit/stackblitz-starters-edrnmq?file=src%2Froutes%2Finit-js%2F%2Bpage.svelte

**Initialization via JS**
- Start the dev server
- Toggle your browser to show mobile mode, visit /init-js
- Click the hamburger men
- Click the backdrop, backdrop closes drawer succesfully

Output in inspector (notice that there is only a single backdrop element)
![image](https://github.com/themesberg/flowbite/assets/9588282/b5239594-8a35-4170-9717-3ef253d0dbea)

**Initialization via data-\* attributes**
- From the previous step, just navigate to /init-data
- Click the backdrop, there will be a leftover backdrop element

Output in inspector (notice the duplicate)
![image](https://github.com/themesberg/flowbite/assets/9588282/1a4be4e4-fe79-494d-a26a-5ec77de2343e)

**Expected behavior**
Drawer toggle should behave the same

**Comment by SiNONiMiTY** [comment]
> I have the same bug with both `Drawer` and `Modal` component.
> 
> When using `data-*` attributes, two backdrop are created and only one is removed when closing.

For the meantime, you can initialize your components via JS. That is the workaround I have been using. Hope the developers notice this issue.

**Comment by SiNONiMiTY** [comment]
@zoltanszogyenyi Can you please help check and assess this issue?

**Comment by haenno** [comment]
@zoltanszogyenyi I can confirm this bug. On click of the hamburger menu, it works all the time. Click in the content part works only every 2nd time correctly. 

See screencast: 

https://github.com/themesberg/flowbite/assets/17815209/24f6e6bb-d3dd-4a3d-aaa1-f9e6ab68e8ec

    "flowbite": "^1.8.1",
    "flowbite-vue": "^0.0.17-next.0",
    "vue": "^3.3.4",

Can also be observed on the demo page of my repo: <https://haenno.github.io/vue-tf/>.
Code can be found here: <https://github.com/haenno/vue-tf/blob/main/src/App.vue>

**Comment by haenno** [comment]
I fixed this for me by changing from `data-drawer-toggle="nav-and-sidebar"` to `data-drawer-hide="nav-and-sidebar"`. Here, **hide** seems to successfully get rid of both the backdrops.

**Comment by rlongre** [comment]
This is being caused by flowbite users calling initFlowbite() in addition to the call to events.init() by the flowbite devs in src/index.ts. 

https://github.com/themesberg/flowbite/blob/f78afe5fe19687fd2d1b62bca143602b58cb9d6b/src/index.ts#L15C1-L29C15

The unavoidable call to events.init() is already calling initDrawers() (and all other init functions) which is the exact same thing that initFlowbite() does when users call it.

https://github.com/themesberg/flowbite/blob/f78afe5fe19687fd2d1b62bca143602b58cb9d6b/src/components/index.ts#L13C1-L25C2

Because initDrawers() in src/components/drawer/index.ts get called twice, document.querySelectorAll('[data-drawer-show]') attaches the click handler to the trigger element twice. This results in Drawer.show() being called twice per click.

https://github.com/themesberg/flowbite/blob/f78afe5fe19687fd2d1b62bca143602b58cb9d6b/src/components/drawer/index.ts#L340C1-L361C8

Drawer.show() then calls _createBackdrop() if the backdrop option is configured.

https://github.com/themesberg/flowbite/blob/f78afe5fe19687fd2d1b62bca143602b58cb9d6b/src/components/drawer/index.ts#L140C1-L143C10

_createBackdrop() then blindly creates a new backdrop rather than checking if one already exists or examining the state of any existing backdrop.

https://github.com/themesberg/flowbite/blob/f78afe5fe19687fd2d1b62bca143602b58cb9d6b/src/components/drawer/index.ts#L159C1-L171C6

As others have stated, the workaround, for now, is to **NOT** call initFlowbite() at all.

If your use case calls for it, you can initialize your components manually but this doesn't seem necessary for now. Because events.init() is always called in src/index.ts, as long as the flowbite library is loaded at all, all of the init functions will still be called. In build configurations that employ tree shaking, you'll need to ensure that your code holds a reference to _ANYTHING_ exported by the flowbite library so the library isn't eliminated during compilation.

In my Angular 16 app, I'm doing this by just holding a reference to the initFlowbite function but never calling it:

``` typescript
import { Component } from '@angular/core';
import { initFlowbite } from 'flowbite';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  private flowbiteReference = initFlowbite;
}
```

**Comment by haenno** [comment]
Thank you for your explanation, @rlongre! 
This gave me great insights in the background of this issue.

Could apply your solution to my Vue App by adding this to my `App.vue`-file...

```ts
<script lang="ts" setup>
  import { initFlowbite } from "flowbite";

  onMounted(() => {
    const flowbiteReferecnce = initFlowbite;
  });
</script>
```

**Comment by jason-e-cruz** [comment]
https://github.com/themesberg/flowbite/pull/665 - this should fix it, not sure what's the review process like since this is my first time making an open-source contribution

**Comment by zoltanszogyenyi** [comment]
Hey peeps!

Flowbite v2.0 is now out and provides a new global Instance Manager.

This means that we now have a better way to manage multiple instances of the same object.

Please check out the following resources:

https://flowbite.com/docs/getting-started/javascript/
https://github.com/themesberg/flowbite/releases/tag/v2.0.0

If there are issues related to this bug still relevant, please re-open.

Cheers,
Zoltan
