### ISSUE TITLE
Cannot find module 'flowbite/plugin' - TailwindCSS, Ruby on Rails, and Importmap

### ISSUE THREAD

**Issue by leoplct** [themesberg/flowbite#754]
**Describe the bug**
I got this error from tailwind.config.js

**Error: Cannot find module 'flowbite/plugin'**
```
Require stack:
/home/runner/work/project/project/config/tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Function.resolve (/snapshot/tailwindcss/standalone-cli/patch-require.js:34:38)
    at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:250334)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:252917)
    at /home/runner/work/project/project/config/tailwind.config.js:74:5
    at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:2556[14](https://github.com/name/project/actions/runs/7275447114/job/19823350019#step:8:15))
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
    at /snapshot/tailwindcss/lib/lib/load-config.js:48:30 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/project/adprojectvigator/config/tailwind.config.js' ]
}
bin/rails aborted!
Command failed with exit 1: /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/tailwindcss-rails-2.1.0-x86_64-linux/exe/x86_64-linux/tailwindcss

Tasks: TOP => test:prepare => tailwindcss:build
(See full trace by running task with --trace)
```

**To Reproduce**

**config/tailwind.config.js**
```
plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
    require('flowbite/plugin'),
    {
      tailwindcss: {},
      autoprefixer: {},
      ...(process.env.NODE_ENV === 'production' ? { cssnano: {} } : {})
    }
  ]
```

**config/importmap.rb**
```
pin "flowbite", to: "https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.turbo.min.js"
pin "flowbite-datepicker", to: "https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/datepicker.turbo.min.js", preload: true

```
**app/javascript/application.js**
```
import 'flowbite';
import 'flowbite-datepicker';
```

**Gemfile**
rails (7.1.2)
tailwindcss-rails (2.1.0-x86_64-darwin)
      railties (>= 6.0.0)

If I remove _require('flowbite/plugin')_ the the CSS is not working properly (see screenshot)

![Screenshot 2023-12-20 at 13 35 41](https://github.com/themesberg/flowbite/assets/1176145/a84aab7a-4b0a-4cb1-8f1f-6d083a61013c)

**Comment by mbhnyc** [comment]
@leoplct any progress on this?  Having similar issues getting all these pieces to play along.

**Comment by leoplct** [comment]
I gave up and switched to standard HTML date field

input type="date" id="start" name="trip-start" value="2018-07-22" min="2018-01-01" max="2018-12-31" />

**Comment by morgler** [comment]
Is this fixed? I tried to switch to Flowbite today, but this error makes me consider other libraries instead :/

**Comment by iwdt** [comment]
I create a solution for standalone tailwindcss - https://github.com/iwdt/flowbite-rails

**Comment by zoltanszogyenyi** [comment]
Hey @leoplct, @mbhnyc, @morgler, @iwdt,

Since `v2.4.1` the datepicker is a core component of Flowbite and with Ruby on Rails you no longer have to separately install the Flowbite Datepicker plugin since it comes out of the box. Please check the new guide here:

https://flowbite.com/docs/getting-started/rails/#datepicker

And the new Flowbite Datepicker API here:

https://flowbite.com/docs/components/datepicker/#javascript-behaviour

Cheers,
Zoltan

**Comment by miguelff** [comment]
+1 on @jbwl [comment](https://github.com/themesberg/flowbite/issues/754#issuecomment-2449524950)

**Comment by david-uhlig** [comment]
I encountered this issue as well. The problem arises because `flowbite/plugin` is not present in the container. When you create a new Rails application using `rails new`, the default `.dockerignore` file excludes the `/node_modules/` directory. As a result, Flowbite and other npm packages are not copied into the container.

```yaml
# Ignore assets.
/node_modules/
/app/assets/builds/*
!/app/assets/builds/.keep
/public/assets
```

https://github.com/rails/rails/blob/ce8a6f126beca56e3183b986e005cd7996b36813/railties/lib/rails/generators/rails/app/templates/dockerignore.tt#L39

This can be solved in two ways:

First, you can remove `/node_modules/` from the `.dockerignore` file. This copies the directory into the container and the build will succeed. I prefer this solution, because it keeps the npm package versions in sync with your project. However, the Rails core team usually have good reasoning for such defaults. Therefore, I am a bit hesitant to do this in light of possible downstream implications.

Second, you can rebuild Flowbite's npm package in the container through the `Dockerfile`, e.g. by adding it right at the beginning of the build block:

```Dockerfile
# Throw-away build stage to reduce size of final image
FROM base AS build

# Install flowbite
RUN apt-get update -qq && \
   apt-get install --no-install-recommends -y npm && \
   npm install flowbite
```

It will be much harder to achieve version parity using this approach, and could introduce subtle bugs due to different npm package versions. At the very least, you probably want to specify the exact version of Flowbite in the `npm install flowbite` line, and be disciplined about keeping it in sync with your development environment.

From Flowbite's perspective, I think it is mainly a documentation issue. Further clarification could prevent others from running into the same issue. Which they probably will, because Rails 8 is heavily marketed towards Kamal 2 and running in Docker containers.

**Comment by domarcio** [comment]
I had the same issue while using Rails 8.0.1 to deploy with Kamal 2. I resolved it by utilizing a Node.js Docker image to specify the Node.js version.

```dockerfile
# Set production environment
...

FROM node:22-alpine AS nodejs
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production

# Copy application code
...
COPY --from=nodejs /app/node_modules ./node_modules
```

**Comment by Set27** [comment]
I don;t use camal, it does not work locally
