### ISSUE TITLE
I can't setup Flowbite JS on a react project

### ISSUE THREAD

**Issue by maelfosso** [themesberg/flowbite#797]
Hello. I am trying to setup Flowbite on a react project without using flowbite-react but it's not working, the dropdown is not displayed
I followed these step
1. Tailwind CSS was working correctly
2. I installed `flowbite (yarn add flowbite)`
3. I updated `tailwind.config.js` like this
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./node_modules/flowbite/**/*.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('flowbite/plugin')
  ],
}
```
4. I updated `public/index.html` by adding before` </body>` this line , `<script src="../node_modules/flowbite/dist/flowbite.min.js"></script>`. I also tried with the CDN  `<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>`

But the dropdown copied from the document it's not working event the accordion.

How to fix that, please?
I DON'T WANT TO USE `flowbite-react` package.

**Comment by dhavalveera** [comment]
https://codesandbox.io/p/sandbox/restless-frost-p56szy


please have a look in the above share codesandboxx link, specifically:

1. `tailwind.config.js`
2. `index.tsx`
3. `styles.css`


I hope this will be helpful as you need to use Flowbite alone, not Flowbite-React and check package.json once for the installation of dependencies of Flowbite, Tailwind

**Comment by zoltanszogyenyi** [comment]
Hey @maelfosso,

Even though we do recommend [Flowbite React](https://flowbite-react.com/) if you want to get the interactive UI components to work, since I think that the CSS and visually everything has rendered correctly, you need to use the `initFlowbite()` function whenever the component has mounted:

https://flowbite.com/docs/getting-started/javascript/#init-functions

Cheers,
Zoltan
