### ISSUE TITLE
When can flowbite-datepicker be used in Vue.js?

### ISSUE THREAD

**Issue by jharefa08** [themesberg/flowbite#827]

**Comment by zoltanszogyenyi** [comment]
Hey @jharefa08,

Since the `v2.4.1` release you can now use the Datepicker component just like any other:

https://flowbite.com/docs/components/datepicker/index.html#javascript-behaviour

I added some examples including with the datepicker in this Vue starter repo: https://github.com/themesberg/tailwind-vue-starter

Cheers,
Zoltan
