### ISSUE TITLE
Figma: Flowbite pro -- almost of out memory

### ISSUE THREAD

**Issue by supermensa** [themesberg/flowbite#988]
**Describe the bug**
After importing the Figma Pro UI to Figma, I get a warning: "Almost out of memory. To avoid losing file access, move some pages to a different file or delete unneeded content" with a link pointing to this page https://help.figma.com/hc/en-us/articles/360040528173-Reduce-memory-usage-in-files

**To Reproduce**
1. Import Figma Pro UI to Figma
2. Read memory warning in left pane.

**Expected behavior**
I'd expect some sort of solution where maybe the components are divided into different files or some other solution to avoid memory loss.

**Comment by robert1508** [comment]
Hello there,

The PC specifications don't matter so much when you work with Figma, because every browser has its own active memory limit. This can differ across devices but the general understanding is there's an active memory limit of 2GB per browser tab and as Figma serves both the web app and the desktop app via a browser, these limitations apply when using the Figma desktop app too.

Considering this aspect, and the fact that Flowbite Figma is a rather large project, there are some recommendations from our side to avoid Memory limit warnings:

1. Publish the Flowbite Figma as a library and then use only the components and pages you need in your new project:

https://www.notion.so/flowbite/Knowledge-center-681d790f1a50405095918d3dfad57f9a.

Considering that Figma uses the memory of the browser (2gb) and not of the computer, try to close the tabs in the browser until it is published.

1. Split our library into smaller libraries:

Due to the fact that Figma recently launched move published component feature, it is now possible to do this and split our library into 3 or more libraries, namely:

- Main components
- Marketing UI
- Application UI

Styles can also be moved, i.e. colors, typography, shadows, and avatars:

https://help.figma.com/hc/en-us/articles/360039820134

If you want to use only one library (which we also recommend), you can move all the pages already created as an example to another file after you have published the library.

This step can reduce the size of your library by up to 50%.

Why don't we split the library into several smaller libraries?

Most of the designers want to have everything in one place to publish Flowbite as the main library and only then to split the library into several pieces if they want that.

Figma currently doesn't let us import more than 1 file at a time without breaking links to instances in the file design system across all pages and components.

Note: we recommend you to best import the entire Flowbite Design System and only then split it as you want, or work with it published as a library.

You can also read more here: https://help.figma.com/hc/en-us/articles/360040528173-Reduce-memory-usage-in-files

All the big design systems for Figma have this problem, we hope that in the future Figma will find a solution because it affects us to the same extent.

We also have a knowledge center here where you can read about how to publish Flowbite as a library and how to connect the published components with your project: [https://flowbite.notion.site/Knowledge-center-681d790f1a50405095918d3dfad57f9a?pvs=74](https://www.notion.so/Knowledge-center-681d790f1a50405095918d3dfad57f9a?pvs=21)

Cheers,
Robert
